#!/bin/sh
CHANGED_FILES_PHP=$(git diff --cached --name-only --diff-filter=ACMR | grep ".php\$" | grep public )

if [ -z "$CHANGED_FILES_PHP" ]
then
    echo "No PHP and VUE files found. No reason to run checks."
    exit 0
else
    set -e

    if [ "$CHANGED_FILES_PHP" ]
    then
        ./vendor/bin/phpcs --standard=./phpcs.xml  $CHANGED_FILES_PHP
        if [ -z "$CHANGED_FILES_PHP" ]
        then
            black --check $CHANGED_FILES_PHP
        fi
    fi
fi
echo "All checks successfully passed."




